title: title omg
theme: minima
author: Lol7425
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:" a adgfgffdggfdgfdfdg
  dcfrghfhkgfhkfhtkhktylutyutyutytyu
# social links
twitter_username: error # DO NOT include the @ character, or else the build will fail!
github_username:  Lol7425 # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
